#!/usr/bin/env node
/**
 * Generate the CLI's terminal identity, `packages/cli/src/identity.ts`, from
 * the Lorekeeper tokens and the Wonder Wagon foundation.
 *
 *   node brand/terminal/build.mjs           write the generated module
 *   node brand/terminal/build.mjs --check   fail if it is stale, or if the
 *                                           two sources disagree
 *
 * Two sources, each owning what it owns. The colour is Lorekeeper's: the dark
 * `accent` from `brand/tokens/tokens.json`, because that file is the source of
 * truth for the palette and nothing downstream hard-codes a value it defines.
 * Everything else is the family's: the serial and the maker from the
 * `lorekeeper` theme in `@wonder-wagon/themes`, the severity mapping from its
 * terminal adapter, and the arithmetic that turns a hex value into the three
 * alphabets a terminal speaks from `@wonder-wagon/tokens/terminal`.
 *
 * The adapter's own choice of colour is deliberately not taken. It paints a
 * theme's `signal`, which for Lorekeeper is the gilt of the star — the second
 * voice, not the mark. Gilt also falls to yellow in sixteen colours, which is
 * both Forge's floor and the `warn` severity. The accent falls to bright blue,
 * which is neither a sibling's colour nor a severity's, and the check below
 * keeps it that way.
 *
 * The result is committed, so the CLI keeps no runtime dependency and its bytes
 * stay deterministic. Nothing here reaches the network or reads a clock.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { terminalIdentity } from '@wonder-wagon/themes/adapters/terminal';
import { lorekeeper } from '@wonder-wagon/themes/lorekeeper';
import { terminalPaint } from '@wonder-wagon/tokens/terminal';

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const TOKENS = join(HERE, '..', 'tokens', 'tokens.json');
const OUT = join(ROOT, 'packages', 'cli', 'src', 'identity.ts');

const themesVersion = require('@wonder-wagon/themes/package.json').version;
const tokensVersion = require('@wonder-wagon/tokens/package.json').version;

/**
 * A TypeScript string literal in the repository's quote style, with every
 * control character escaped so the committed file carries no raw escape byte.
 *
 * @param {string} text
 * @returns {string}
 */
function quote(text) {
  const escaped = text
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\u001B', '\\u001B');
  return `'${escaped}'`;
}

/** @returns {{ source: string, problems: string[] }} */
function generate() {
  const tokens = JSON.parse(readFileSync(TOKENS, 'utf8'));
  const accent = {
    day: tokens.color.light.accent.value,
    night: tokens.color.dark.accent.value,
  };

  const family = terminalIdentity(lorekeeper, 'night');
  const brand = terminalPaint(accent.night);
  const problems = [];

  // The foundation carries a copy of Lorekeeper's hue as the theme's `link`.
  // A copy that drifts is two sources of truth, so disagreement fails here
  // rather than surfacing as a second, unmeasured indigo somewhere else.
  for (const env of ['day', 'night']) {
    if (lorekeeper.link[env].toUpperCase() !== accent[env].toUpperCase()) {
      problems.push(
        `@wonder-wagon/themes lorekeeper.link.${env} is ${lorekeeper.link[env]} but tokens.json accent is ${accent[env]}`,
      );
    }
  }
  // Colour never carries meaning here, but it must not look like it does:
  // at the sixteen-colour floor the identity may not share a severity's hue.
  if (Object.values(family.severity).includes(brand.ansi16Name)) {
    problems.push(
      `the accent falls to ${brand.ansi16Name} in sixteen colours, which is a severity colour`,
    );
  }

  const source = [
    '// GENERATED by brand/terminal/build.mjs — do not edit.',
    `// Colour: brand/tokens/tokens.json ${tokens.version}, dark accent ${brand.hex}.`,
    `// Serial, severity and terminal arithmetic: @wonder-wagon/themes@${themesVersion}, @wonder-wagon/tokens@${tokensVersion}, theme '${lorekeeper.id}'.`,
    '// Regenerate with `npm run brand:terminal`; verify with `npm run brand:terminal:check`.',
    '',
    "/** The product's serial and the family maker's mark: stated once, printed small. */",
    `export const SERIAL = ${quote(family.serial)};`,
    '',
    '/** The accent, in every alphabet a terminal speaks. Severity never uses it. */',
    'export const BRAND = Object.freeze({',
    `  hex: ${quote(brand.hex)},`,
    `  truecolor: ${quote(brand.truecolor)},`,
    `  ansi256: ${quote(brand.ansi256)},`,
    `  ansi16: ${quote(brand.ansi16)},`,
    '});',
    '',
    "/** Severity maps to the terminal's own colours, which render the same everywhere. */",
    'export const SEVERITY = Object.freeze({',
    ...Object.entries(family.severity).map(([k, v]) => `  ${k}: ${quote(v)},`),
    '});',
    '',
  ].join('\n');

  return { source, problems };
}

function main() {
  const check = process.argv.includes('--check');
  const { source, problems } = generate();
  const where = relative(ROOT, OUT);

  for (const problem of problems) {
    console.error(`brand terminal: ${problem}`);
  }
  if (problems.length > 0) {
    process.exitCode = 1;
    return;
  }

  if (!check) {
    writeFileSync(OUT, source);
    console.log(`wrote ${where}`);
    return;
  }

  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    current = '';
  }
  if (current !== source) {
    console.error(
      `brand terminal: ${where} is stale; run \`npm run brand:terminal\`.`,
    );
    process.exitCode = 1;
    return;
  }
  console.log(`brand terminal check clean: ${where} is current.`);
}

main();
