/**
 * The service worker, generated so its page list is the site's own.
 *
 * Offline behaviour, stated plainly: on first load with a connection it saves
 * every page in the contents, the offline page, and every built asset those
 * pages reference. After that the saved pages work with no connection. Online,
 * pages come from the network first, so a reader never sees a stale page while
 * connected. A page that was never saved gets the offline page, which says so.
 * The worker requests nothing but this site's own files.
 */

import type { APIRoute } from 'astro';
import { OFFLINE, PAGES } from '../lib/nav';

/** Bumped by hand only when the caching strategy itself changes. */
const CACHE = 'lorekeeper-docs-1';

function worker(pages: readonly string[], offline: string): string {
  return `// Lorekeeper docs service worker. Generated by apps/docs/src/pages/sw.js.ts.
const CACHE = ${JSON.stringify(CACHE)};
const PAGES = ${JSON.stringify(pages)};
const OFFLINE = ${JSON.stringify(offline)};
const ASSET = /["'](\\/_astro\\/[^"']+)["']/g;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const assets = new Set();
    for (const url of [...PAGES, OFFLINE, '/manifest.webmanifest']) {
      const response = await fetch(url, { cache: 'no-cache' });
      if (!response.ok) continue;
      await cache.put(url, response.clone());
      for (const match of (await response.text()).matchAll(ASSET)) assets.add(match[1]);
    }
    await cache.addAll([...assets]);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

/** /concepts and /concepts/ are one page. */
function keys(url) {
  const path = new URL(url).pathname;
  return path.endsWith('/') || path.includes('.') ? [path] : [path, path + '/'];
}

async function fromCache(url) {
  const cache = await caches.open(CACHE);
  for (const key of keys(url)) {
    const hit = await cache.match(key);
    if (hit) return hit;
  }
  return undefined;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // Hashed build assets never change under one name: cache first.
  if (new URL(request.url).pathname.startsWith('/_astro/')) {
    event.respondWith((async () => (await fromCache(request.url)) ?? fetch(request))());
    return;
  }

  // Everything else: the network first, the saved copy when offline.
  event.respondWith((async () => {
    try {
      const response = await fetch(request);
      if (response.ok) {
        const cache = await caches.open(CACHE);
        await cache.put(request, response.clone());
      }
      return response;
    } catch (error) {
      const saved = await fromCache(request.url);
      if (saved) return saved;
      if (request.mode === 'navigate') {
        const offline = await fromCache(new URL(OFFLINE, self.location.origin).href);
        if (offline) return offline;
      }
      throw error;
    }
  })());
});
`;
}

export const GET: APIRoute = () =>
  new Response(
    worker(
      PAGES.map((p) => p.href),
      OFFLINE.href,
    ),
    { headers: { 'Content-Type': 'text/javascript; charset=utf-8' } },
  );
