// GENERATED by brand/terminal/build.mjs — do not edit.
// Colour: brand/tokens/tokens.json 0.1.0, dark accent #99A2F0.
// Serial, severity and terminal arithmetic: @wonder-wagon/themes@0.1.0, @wonder-wagon/tokens@0.1.0, theme 'lorekeeper'.
// Regenerate with `npm run brand:terminal`; verify with `npm run brand:terminal:check`.

/** The product's serial and the family maker's mark: stated once, printed small. */
export const SERIAL = 'LK-047';

/** The accent, in every alphabet a terminal speaks. Severity never uses it. */
export const BRAND = Object.freeze({
  hex: '#99A2F0',
  truecolor: '\u001B[38;2;153;162;240m',
  ansi256: '\u001B[38;5;111m',
  ansi16: '\u001B[1m\u001B[34m',
});

/** Severity maps to the terminal's own colours, which render the same everywhere. */
export const SEVERITY = Object.freeze({
  ok: 'green',
  info: 'cyan',
  warn: 'yellow',
  bad: 'red',
});
