// GENERATED by wonder-wagon-ui/cli — do not edit.
// Product: Lorekeeper; values hash: e94da0e0.
// Generate at build time, commit this file, and verify it with the product's --check script.

export const PRODUCT = Object.freeze({
  "name": "Lorekeeper",
  "serial": "LK-047",
  "tagline": "Pathfinder finds the way; Lorekeeper remembers the journey.",
  "accent": "#99A2F0",
  "secondary": "#E2B45C",
  "ansi16": {
    "accent": {
      "name": "blue",
      "bright": true
    },
    "secondary": {
      "name": "yellow",
      "bright": false
    }
  },
  "mark": {
    "width": 8,
    "nameRow": 2,
    "rows": [
      {
        "expressive": [
          {
            "text": "  ╭───╮",
            "role": "accent"
          }
        ],
        "plain": "  .---."
      },
      {
        "expressive": [
          {
            "text": " ╭╯   ╰╮",
            "role": "accent"
          }
        ],
        "plain": " /     \\"
      },
      {
        "expressive": [
          {
            "text": " │  ",
            "role": "accent"
          },
          {
            "text": "✦",
            "role": "secondary"
          },
          {
            "text": "  │",
            "role": "accent"
          }
        ],
        "plain": " |  *  |"
      },
      {
        "expressive": [
          {
            "text": " ╰╮   ╭╯",
            "role": "accent"
          }
        ],
        "plain": " \\     /"
      },
      {
        "expressive": [
          {
            "text": "  ╰───╯",
            "role": "accent"
          }
        ],
        "plain": "  '---'"
      }
    ]
  },
  "letterspace": true
} as const);
export const PAINTS = Object.freeze({
  "accent": {
    "hex": "#99A2F0",
    "truecolor": "\u001b[38;2;153;162;240m",
    "ansi256": "\u001b[38;5;111m",
    "ansi256Index": 111,
    "ansi16": "\u001b[1m\u001b[34m",
    "ansi16Name": "blue",
    "ansi16Bright": true
  },
  "secondary": {
    "hex": "#E2B45C",
    "truecolor": "\u001b[38;2;226;180;92m",
    "ansi256": "\u001b[38;5;179m",
    "ansi256Index": 179,
    "ansi16": "\u001b[33m",
    "ansi16Name": "yellow",
    "ansi16Bright": false
  }
} as const);
export const VALUES_HASH = "e94da0e0";
const RESET = "\u001B[0m";
const DIM = "\u001B[2m";
const cells = (text: string) => [...text].length;
const spacedName = () => PRODUCT.letterspace ? [...PRODUCT.name.toUpperCase()].join(" ") : PRODUCT.name;
const paint = (text: string, role: "accent" | "secondary", caps: { depth: 0 | 4 | 8 | 24 }) => {
  if (caps.depth === 0 || text === "") return text;
  const palette = role === "secondary" && PAINTS.secondary ? PAINTS.secondary : PAINTS.accent;
  const open = caps.depth === 24 ? palette.truecolor : caps.depth === 8 ? palette.ansi256 : palette.ansi16;
  return open + text + RESET;
};
const dim = (text: string, caps: { depth: 0 | 4 | 8 | 24 }) => caps.depth === 0 || text === "" ? text : DIM + text + RESET;

export function detectTerminal(input: { env: Readonly<Record<string, string | undefined>>; isTTY: boolean; columns?: number; platform?: string }) {
  const env = input.env;
  const color = env.FORCE_COLOR === "0" || env.NO_COLOR !== undefined || env.TERM === "dumb"
    ? false
    : env.FORCE_COLOR !== undefined ? true : input.isTTY;
  const platform = input.platform ?? "linux";
  const unicode = env.WW_ASCII === "1" ? false : platform === "win32"
    ? Boolean(env.WT_SESSION) || env.TERM_PROGRAM === "vscode"
    : /utf-?8/i.test(env.LC_ALL || env.LC_CTYPE || env.LANG || "");
  const depth = !color ? 0 : env.FORCE_COLOR === "3" ? 24 : env.FORCE_COLOR === "2" ? 8
    : /^(truecolor|24bit)$/i.test(env.COLORTERM ?? "") || /-direct$/i.test(env.TERM ?? "") ? 24
    : /256color/i.test(env.TERM ?? "") ? 8 : 4;
  const tier = !input.isTTY ? "contract" : color && unicode ? "expressive" : "plain";
  const columns = Number.isInteger(input.columns) && (input.columns ?? 0) > 0 ? input.columns as number : 80;
  return Object.freeze({ tier, depth, unicode, columns });
}

export function renderCliIdentity(options: { version: string; caps: { tier: "contract" | "plain" | "expressive"; depth: 0 | 4 | 8 | 24; unicode: boolean; columns: number }; form?: "block" | "line"; machine?: boolean }) {
  const caps = options.caps;
  if (options.machine === true || caps.tier === "contract") return "";
  const name = spacedName();
  const metadata = "v" + options.version + " " + (caps.unicode ? "·" : "-") + " " + PRODUCT.serial;
  const nameLine = paint(name, "accent", caps) + "  " + dim(metadata, caps);
  const lineCells = cells(name) + 2 + cells(metadata);
  const blockCells = 2 + PRODUCT.mark.width + 4 + lineCells;
  const form = caps.columns < blockCells ? "line" : (options.form ?? "block");
  if (form === "line") return nameLine;
  const textColumn = PRODUCT.mark.width + 4;
  const lines = PRODUCT.mark.rows.map((row, index) => {
    const raw = caps.unicode ? row.expressive.map((segment) => segment.text).join("") : row.plain;
    const mark = caps.unicode ? row.expressive.map((segment) => {
      const role: "accent" | "secondary" | "dim" = segment.role;
      return String(role) === "dim" ? dim(segment.text, caps)
        : paint(segment.text, role === "secondary" && PAINTS.secondary ? "secondary" : "accent", caps);
    }).join("") : paint(row.plain, "accent", caps);
    const padding = " ".repeat(textColumn - cells(raw));
    if (index === PRODUCT.mark.nameRow) return "  " + mark + padding + nameLine;
    if (index === PRODUCT.mark.nameRow + 1) return "  " + mark + padding + dim(PRODUCT.tagline, caps);
    return "  " + mark;
  });
  return "\n" + lines.join("\n") + "\n";
}
